// Lab_03_1.cpp
// < Коцюба Остап >
// Лабораторна робота No 3.1
// Розгалуження, задане формулою: функція однієї змінної.
// Варіант 4
#include <iostream>
#include <cmath>
using namespace std;
int main()
{
	double x; 
	double y; 
	double A; 
	double B; 
	cout << "x = "; cin >> x;
	A = x+1;
	// спосіб 1
	if (x <= 4)
		B = exp(log(2 + 2*x) + 2*x);
	if (4 < x && x <= 7)
		B = 1/tan((1+x)/9+8*x);
	if (x > 7)
		B = 1-7*x+x*x-2*x*x*x;
	y = A + B;
	cout << endl;
	cout << "1) y = " << y << endl;
	// спосіб 2
	if (x <= 4)
		B = exp(log(2 + 2 * x) + 2 * x);
	else
		if (x > 7)
			B = 1 - 7 * x + x * x - 2 * x * x * x;
		else
			B = 1 / tan((1 + x) / 9 + 8 * x);
	y = A + B;
	cout << "2) y = " << y << endl;
	cin.get();
	return 0;
}
